name: Run tests

on:
  pull_request:

jobs:

  flake8:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2.4.0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.8

      - uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-flake8

      - name: Install flake8
        run: |
          pip install --upgrade --upgrade-strategy eager flake8 flake8-print flake8-blind-except pep8-naming

      - name: Lint with flake8
        run: flake8

  black:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2.4.0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.8

      - uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-black

      - name: Install black
        run: |
          pip install --upgrade --upgrade-strategy eager black

      - name: Test formatting with black
        run: black --check .

  isort:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2.4.0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.8

      - uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-isort

      - name: Install isort
        run: |
          pip install --upgrade --upgrade-strategy eager isort

      - name: Test imports with isort
        run: isort --check .

  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2.4.0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.8
      
      - name: Test with pytest
        run: pytest tests/test_report_example.py
